name: "Manual_Workflow"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        type: string
        default: 'test input'
      

jobs:
  manual_demo:
    runs-on: ubuntu-latest

    steps:
      - name: "manual created workflow"
        run: echo "manual workflow triggerd successfully!"
