name: "Manual_Workflow"

on:
  workflow_dispatch:

jobs:
  manual_demo:
    runs-on: ubuntu-latest

    steps:
      - name: "manual created workflow"
        run: echo "manual workflow triggerd successfully!"
