name: practice_demo

on:
  push:
    branches: [main]

jobs:
  demo-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
    
      - name: "Testing practice demo-build workflow"
        run: echo "workflow build successfully"

  workflow-calling:
    uses: ./.github/workflows/workflow_calling.yml
    with:
      env: production
        
  Deploy-build:
    runs-on: ubuntu-latest
    needs: demo-build
    steps:
      - name: Deployed workflow
        run: echo "Deployed the build successfully"
      
    
      
      

